/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:newUser:519552:
  println("newUser - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:newUser:519552:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:969126:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:969126:

public void button1_click2(GButton source, GEvent event) { //_CODE_:button1:471985:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:471985:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:900753:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:900753:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:379613:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:379613:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:878802:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:878802:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  newUser = new GButton(this, 200, 100, 80, 30);
  newUser.setText("New User");
  newUser.addEventHandler(this, "button1_click1");
  dropList1 = new GDropList(this, 400, 100, 90, 220, 10, 10);
  dropList1.setItems(loadStrings("list_969126"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  button1 = new GButton(this, 300, 100, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click2");
  textfield1 = new GTextField(this, 550, 80, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield2 = new GTextField(this, 550, 115, 120, 30, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  button2 = new GButton(this, 275, 250, 391, 171);
  button2.setText("getData");
  button2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton newUser; 
GDropList dropList1; 
GButton button1; 
GTextField textfield1; 
GTextField textfield2; 
GButton button2; 
